content = (
    'CONFIG_IDF_TARGET="esp32"\n'
    'CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y\n'
    'CONFIG_ESPTOOLPY_FLASHSIZE="4MB"\n'
    'CONFIG_ESPTOOLPY_FLASHMODE_DIO=y\n'
    'CONFIG_ESPTOOLPY_FLASHFREQ_80M=y\n'
    'CONFIG_ESP32_SPIRAM_SUPPORT=y\n'
    'CONFIG_SPIRAM_MODE_QUAD=y\n'
    'CONFIG_SPIRAM_TYPE_AUTO=y\n'
    'CONFIG_SPIRAM_SIZE=-1\n'
    'CONFIG_SPIRAM_SPEED_80M=y\n'
    'CONFIG_SPIRAM_BOOT_INIT=y\n'
    'CONFIG_SPIRAM_USE_MALLOC=y\n'
    'CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=4096\n'
    'CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=32768\n'
    'CONFIG_PARTITION_TABLE_CUSTOM=y\n'
    'CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions.csv"\n'
    'CONFIG_PARTITION_TABLE_OFFSET=0x8000\n'
    'CONFIG_ESP_MAIN_TASK_STACK_SIZE=8192\n'
    'CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM=4\n'
    'CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM=8\n'
    'CONFIG_EXAMPLE_WIFI_SSID="iPhone (3)"\n'
    'CONFIG_EXAMPLE_WIFI_PASSWORD="24006556766"\n'
)

with open('sdkconfig.defaults', 'w', encoding='ascii', newline='\n') as f:
    f.write(content)

print('Done: sdkconfig.defaults generated successfully')
